utils.el: replace `add-to-list` with `push`
`add-to-list` can't be used with lexical binding, which is probably
why its documentation discourages the use. So replace this with `push`

Fixes compilation error:

    In refman2func-doc:
    utils.el:29:12: Error: ‘add-to-list’ can’t use lexical var ‘functions’; use ‘push’ or ‘cl-pushnew’